# Generated by Django 5.1 on 2024-08-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='performer',
            new_name='executor',
        ),
        migrations.AlterField(
            model_name='labelinfo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='Task'),
        ),
    ]
